version: "3.8"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    env_file: 
    - docker.env 
  test-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432" # 👈 Note the 5433 port (since we are using 5432 for our regular db)
    environment:
      POSTGRES_PASSWORD: pass123
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file: 
    - docker.env
    ports:
      - "5050:80"